# frozen_string_literal: true

# Create a sample Teuton test to try teuton-panel without student machines.
# Every case runs on localhost, so Teuton only needs Ruby on this machine.
#
# Usage: ruby create_sandbox.rb [DIRPATH]   (default: tmp/sandbox)

require "fileutils"
require "yaml"

START_RB = <<~RUBY
  group "Sandbox" do
    target "Ruby is installed", weight: 1
    run "ruby -v", on: :host1
    expect "ruby"

    target "Student knows 2 + 2", weight: 2
    run "ruby -e \\"puts 2 + 2\\"", on: :host1
    expect get(:answer)
  end

  play do
    show
    export
  end
RUBY

CONFIG_YAML = <<~YAML
  # Sandbox test generated by the teuton-sandbox skill.
  # tt_include: directory with one YAML file per registered student.
  global:
    tt_include: config.d
  cases: []
YAML

PARAMS_YAML = <<~YAML
  # Registration fields for teuton-panel and how each one is filled.
  tt_members: AS NAME
  tt_moodle_id: AS EMAIL
  answer: ASK
  host1_ip: AUTO IP
YAML

STUDENTS = [
  {"tt_members" => "Ana", "tt_moodle_id" => "ana@example.com", "answer" => "4", "tt_panel_code" => "AB3K", "tt_source_ip" => "192.168.1.21"},
  {"tt_members" => "Luis", "tt_moodle_id" => "luis@example.com", "answer" => "5", "tt_panel_code" => "CD4M", "tt_source_ip" => "192.168.1.22"},
  {"tt_members" => "Marta", "tt_moodle_id" => "marta@example.com", "answer" => "4", "tt_panel_code" => "EF5N", "tt_source_ip" => "192.168.1.23"},
  {"tt_members" => "Pablo", "tt_moodle_id" => "pablo@example.com", "answer" => "4", "tt_panel_code" => "GH6P", "tt_source_ip" => "192.168.1.24", "tt_panel_disabled" => true}
]

def create_file(filepath, content)
  File.write(filepath, content)
  puts "* Create file       => #{filepath}"
end

dirpath = ARGV[0] || File.join("tmp", "sandbox")
if Dir.exist?(dirpath)
  warn "[ERROR] create_sandbox: directory already exists! <#{dirpath}>"
  warn "[ERROR] Remove it first or choose another path."
  exit 1
end

configdir = File.join(dirpath, "test-sandbox", "config.d")
FileUtils.mkdir_p(configdir)
puts "* Create dir        => #{configdir}"

testdir = File.dirname(configdir)
create_file(File.join(testdir, "start.rb"), START_RB)
create_file(File.join(testdir, "config.yaml"), CONFIG_YAML)
create_file(File.join(testdir, "teuton-panel-params.yaml"), PARAMS_YAML)
STUDENTS.each do |student|
  data = student.merge("host1_ip" => "localhost")
  create_file(File.join(configdir, "#{student["tt_panel_code"]}.yaml"), data.to_yaml)
end

puts "==> [INFO] Sandbox ready: #{dirpath}"
